name: jamespaul
favicon: null
layout_spectrum: 0.5891865966841578
typography_spectrum: 0.9570767991244793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5539545053616166
  lightness: 0.4091776176355779
  saturation: 0.8160655915271491
  rhythmicContrast: 0.8925324820447713
purpose: []
